# quiz_data.py
quizzes = {
    "capitals": [
        {"question": "What is the capital of France?", "options": ["Berlin", "Paris", "Madrid", "Rome"], "answer": "Paris"},
        {"question": "What is the capital of Germany?", "options": ["Berlin", "Paris", "Madrid", "Rome"], "answer": "Berlin"},
        {"question": "What is the capital of Spain?", "options": ["Berlin", "Paris", "Madrid", "Rome"], "answer": "Madrid"},
        {"question": "What is the capital of Italy?", "options": ["Berlin", "Paris", "Madrid", "Rome"], "answer": "Rome"},
        {"question": "What is the capital of the United States?", "options": ["New York", "Los Angeles", "Washington, D.C.", "Chicago"], "answer": "Washington, D.C."},
        {"question": "What is the capital of Canada?", "options": ["Toronto", "Vancouver", "Ottawa", "Montreal"], "answer": "Ottawa"},
        {"question": "What is the capital of Australia?", "options": ["Sydney", "Melbourne", "Canberra", "Brisbane"], "answer": "Canberra"},
        {"question": "What is the capital of Brazil?", "options": ["São Paulo", "Rio de Janeiro", "Brasília", "Salvador"], "answer": "Brasília"},
        {"question": "What is the capital of Japan?", "options": ["Osaka", "Tokyo", "Kyoto", "Nagoya"], "answer": "Tokyo"},
        {"question": "What is the capital of Russia?", "options": ["Saint Petersburg", "Moscow", "Kazan", "Sochi"], "answer": "Moscow"},
        {"question": "What is the capital of South Africa?", "options": ["Pretoria", "Cape Town", "Johannesburg", "Durban"], "answer": "Pretoria"},
        {"question": "What is the capital of China?", "options": ["Shanghai", "Beijing", "Guangzhou", "Shenzhen"], "answer": "Beijing"},
        {"question": "What is the capital of India?", "options": ["Mumbai", "New Delhi", "Bangalore", "Kolkata"], "answer": "New Delhi"},
        {"question": "What is the capital of Argentina?", "options": ["Córdoba", "Rosario", "Buenos Aires", "Mendoza"], "answer": "Buenos Aires"},
        {"question": "What is the capital of Egypt?", "options": ["Alexandria", "Cairo", "Luxor", "Giza"], "answer": "Cairo"},
    ],
    "flags": [
        {"question": "<img src='/static/img/flags/usa.png' alt='Flag of USA'>", "options": ["United States", "Canada", "Mexico", "Brazil"], "answer": "United States"},
        {"question": "<img src='/static/img/flags/japan.png' alt='Flag of Japan'>", "options": ["China", "Japan", "South Korea", "Vietnam"], "answer": "Japan"},
        {"question": "<img src='/static/img/flags/germany.png' alt='Flag of Germany'>", "options": ["Austria", "Belgium", "Germany", "Netherlands"], "answer": "Germany"},
        {"question": "<img src='/static/img/flags/france.png' alt='Flag of France'>", "options": ["Italy", "France", "Spain", "Portugal"], "answer": "France"},
        {"question": "<img src='/static/img/flags/brazil.png' alt='Flag of Brazil'>", "options": ["Argentina", "Brazil", "Colombia", "Chile"], "answer": "Brazil"},
        {"question": "<img src='/static/img/flags/india.png' alt='Flag of India'>", "options": ["Pakistan", "India", "Sri Lanka", "Bangladesh"], "answer": "India"},
        {"question": "<img src='/static/img/flags/canada.png' alt='Flag of Canada'>", "options": ["United States", "Canada", "United Kingdom", "Australia"], "answer": "Canada"},
        {"question": "<img src='/static/img/flags/south_africa.png' alt='Flag of South Africa'>", "options": ["Kenya", "South Africa", "Nigeria", "Ghana"], "answer": "South Africa"},
        {"question": "<img src='/static/img/flags/australia.png' alt='Flag of Australia'>", "options": ["New Zealand", "Australia", "United Kingdom", "Fiji"], "answer": "Australia"},
        {"question": "<img src='/static/img/flags/italy.png' alt='Flag of Italy'>", "options": ["France", "Italy", "Spain", "Greece"], "answer": "Italy"}
    ],
    "random_geography": [
        {"question": "What is the longest river in the world?",
         "options": ["Amazon River", "Nile River", "Yangtze River", "Mississippi River"], "answer": "Amazon River"},
        {"question": "Which country is known as the Land of the Rising Sun?",
         "options": ["China", "South Korea", "Japan", "Thailand"], "answer": "Japan"},
        {"question": "What is the capital city of Australia?",
         "options": ["Sydney", "Melbourne", "Canberra", "Brisbane"], "answer": "Canberra"},
        {"question": "Which continent is the Sahara Desert located in?",
         "options": ["Africa", "Asia", "North America", "Australia"], "answer": "Africa"},
        {"question": "What is the smallest country in the world by land area?",
         "options": ["Monaco", "Vatican City", "Nauru", "San Marino"], "answer": "Vatican City"},
        {"question": "Which country has the most volcanoes?",
         "options": ["Indonesia", "Japan", "Iceland", "United States"], "answer": "Indonesia"},
        {"question": "Which mountain range is Mount Everest part of?",
         "options": ["Andes", "Rockies", "Himalayas", "Alps"], "answer": "Himalayas"},
        {"question": "What is the largest country in the world by area?",
         "options": ["United States", "Canada", "China", "Russia"], "answer": "Russia"},
        {"question": "Which country is both an island and a continent?",
         "options": ["Australia", "New Zealand", "Indonesia", "Madagascar"], "answer": "Australia"},
        {"question": "Which ocean is the largest in the world?",
         "options": ["Atlantic Ocean", "Indian Ocean", "Arctic Ocean", "Pacific Ocean"], "answer": "Pacific Ocean"},
        {"question": "What is the largest desert in the world?",
         "options": ["Kalahari Desert", "Gobi Desert", "Sahara Desert", "Antarctic Desert"],
         "answer": "Antarctic Desert"},
        {"question": "Which country has the most official languages?",
         "options": ["India", "Switzerland", "South Africa", "Belgium"], "answer": "South Africa"},
        {"question": "Which U.S. state has the most national parks?",
         "options": ["California", "Alaska", "Utah", "Arizona"], "answer": "California"},
        {"question": "What is the tallest waterfall in the world?",
         "options": ["Niagara Falls", "Victoria Falls", "Angel Falls", "Iguazu Falls"], "answer": "Angel Falls"}
    ],
    "scotland": [
        {"question": "Who was the Scottish leader at the Battle of Bannockburn in 1314?", "options": ["William Wallace", "Robert the Bruce", "James I", "David II"], "answer": "Robert the Bruce"},
        {"question": "What year did the Treaty of Union, forming the Kingdom of Great Britain, take effect?", "options": ["1603", "1707", "1746", "1820"], "answer": "1707"},
        {"question": "Which Scottish king was known as 'The Hammer of the Scots'?", "options": ["Edward I", "Alexander III", "James IV", "Malcolm Canmore"], "answer": "Edward I"},
        {"question": "What is the name of the battle where the Jacobite forces were defeated in 1746?", "options": ["Battle of Falkirk", "Battle of Bannockburn", "Battle of Culloden", "Battle of Stirling Bridge"], "answer": "Battle of Culloden"},
        {"question": "Who was the famous Scottish queen executed by Elizabeth I of England?", "options": ["Mary, Queen of Scots", "Margaret Tudor", "Elizabeth Stuart", "Anne of Denmark"], "answer": "Mary, Queen of Scots"},
        {"question": "What was the name of the rebellion led by Bonnie Prince Charlie?", "options": ["The Glorious Revolution", "The Jacobite Rising", "The Darien Scheme", "The Covenanting Wars"], "answer": "The Jacobite Rising"},
        {"question": "Which ancient Scottish tribe is credited with building the standing stones on Orkney?", "options": ["Picts", "Scots", "Gaels", "Britons"], "answer": "Picts"},
        {"question": "What is the name of the Scottish Declaration of Independence signed in 1320?", "options": ["Magna Carta", "Declaration of Arbroath", "Treaty of Edinburgh", "Act of Union"], "answer": "Declaration of Arbroath"},
        {"question": "What was the primary goal of the Darien Scheme in the 1690s?", "options": ["Colonizing Panama", "Conquering England", "Reclaiming lost land from the Picts", "Defending Scotland from Viking attacks"], "answer": "Colonizing Panama"},
        {"question": "Which Scottish saint is known as the Apostle of Scotland?", "options": ["St. Columba", "St. Patrick", "St. Andrew", "St. Ninian"], "answer": "St. Columba"},
        {"question": "Where is the Stone of Destiny traditionally kept?", "options": ["Edinburgh Castle", "Scone Palace", "Holyrood Abbey", "Stirling Castle"], "answer": "Scone Palace"},
        {"question": "Which famous Scottish inventor is credited with improving the steam engine in the 18th century?", "options": ["Alexander Graham Bell", "James Watt", "John Logie Baird", "Adam Smith"], "answer": "James Watt"},
        {"question": "Which Scottish city became known as the 'Athens of the North' during the Enlightenment?", "options": ["Edinburgh", "Glasgow", "Aberdeen", "Dundee"], "answer": "Edinburgh"},
        {"question": "What event led to the massacre of the Clan MacDonald in 1692?", "options": ["The Battle of Glencoe", "The Darien Scheme", "The Signing of the Solemn League", "The Highland Clearances"], "answer": "The Battle of Glencoe"},
        {"question": "What historic Scottish fortress was the birthplace of Mary, Queen of Scots?", "options": ["Edinburgh Castle", "Linlithgow Palace", "Stirling Castle", "Dunnottar Castle"], "answer": "Linlithgow Palace"}
    ],
    "ireland": [
        {"question": "Who was the first President of Ireland?", "options": ["Douglas Hyde", "Eamon de Valera", "Michael Collins", "John F. Kennedy"], "answer": "Douglas Hyde"},
        {"question": "In what year did Ireland gain independence from Britain?", "options": ["1916", "1922", "1937", "1949"], "answer": "1922"},
        {"question": "What was the name of the Irish rebellion in 1916?", "options": ["Easter Rising", "Irish Civil War", "Great Irish Rebellion", "Battle of the Boyne"], "answer": "Easter Rising"},
        {"question": "Who is known as the 'Liberator' of Ireland?", "options": ["Daniel O'Connell", "Patrick Pearse", "James Connolly", "Michael Collins"], "answer": "Daniel O'Connell"},
        {"question": "Which Irish writer won the Nobel Prize in Literature in 1923?", "options": ["James Joyce", "William Butler Yeats", "Samuel Beckett", "George Bernard Shaw"], "answer": "William Butler Yeats"},
        {"question": "What was the name of the treaty that ended the Irish War of Independence?", "options": ["Treaty of Versailles", "Treaty of Paris", "Anglo-Irish Treaty", "Treaty of Dublin"], "answer": "Anglo-Irish Treaty"},
        {"question": "What famous Irish political leader was assassinated in 1922?", "options": ["Michael Collins", "Eamon de Valera", "Arthur Griffith", "John Redmond"], "answer": "Michael Collins"},
        {"question": "What year did the Irish Republic officially declare its independence?", "options": ["1916", "1919", "1921", "1937"], "answer": "1919"},
        {"question": "What was the name of the Irish nationalist movement founded in the late 19th century?", "options": ["Irish Republican Army", "Sinn Féin", "Gaelic League", "Irish Nationalist League"], "answer": "Gaelic League"},
        {"question": "Who was the first woman to be elected as a Member of the Dáil (Irish Parliament)?", "options": ["Constance Markievicz", "Eamon de Valera", "Mary Robinson", "Rosie Hackett"], "answer": "Constance Markievicz"},
        {"question": "Which famous Irish rock band was formed in Dublin in 1976?", "options": ["The Cranberries", "U2", "The Dubliners", "The Pogues"], "answer": "U2"},
        {"question": "Which Irish city is known as the birthplace of St. Patrick?", "options": ["Dublin", "Belfast", "Armagh", "Downpatrick"], "answer": "Downpatrick"},
        {"question": "What year did the Great Famine begin in Ireland?", "options": ["1841", "1845", "1850", "1860"], "answer": "1845"},
        {"question": "What battle took place in 1690 between the forces of King William III and King James II of England?", "options": ["Battle of Clontarf", "Battle of the Boyne", "Battle of Aughrim", "Battle of Ballaghmoon"], "answer": "Battle of the Boyne"},
        {"question": "Which Irish king was defeated by the English at the Battle of Kinsale in 1601?", "options": ["Brian Boru", "Hugh O'Neill", "Red Hugh O'Donnell", "Donnchadh mac Cárthaigh"], "answer": "Hugh O'Neill"}
],
    "usa": [
        {"question": "Who was the first President of the United States?", "options": ["Thomas Jefferson", "Abraham Lincoln", "George Washington", "John Adams"], "answer": "George Washington"},
        {"question": "In what year did the United States declare its independence?", "options": ["1776", "1783", "1800", "1812"], "answer": "1776"},
        {"question": "Which event marked the start of the American Civil War?", "options": ["Battle of Gettysburg", "Bombardment of Fort Sumter", "Emancipation Proclamation", "Boston Tea Party"], "answer": "Bombardment of Fort Sumter"},
        {"question": "Who wrote the Declaration of Independence?", "options": ["Benjamin Franklin", "Thomas Jefferson", "John Adams", "James Madison"], "answer": "Thomas Jefferson"},
        {"question": "What year was the U.S. Constitution ratified?", "options": ["1776", "1781", "1787", "1791"], "answer": "1787"},
        {"question": "Which U.S. President issued the Emancipation Proclamation?", "options": ["George Washington", "Abraham Lincoln", "Ulysses S. Grant", "Theodore Roosevelt"], "answer": "Abraham Lincoln"},
        {"question": "What was the primary reason for the U.S. Civil War?", "options": ["Slavery", "State Rights", "Territorial Expansion", "Economic Differences"], "answer": "Slavery"},
        {"question": "Who was the U.S. President during the Great Depression?", "options": ["Franklin D. Roosevelt", "Herbert Hoover", "Woodrow Wilson", "Harry S. Truman"], "answer": "Franklin D. Roosevelt"},
        {"question": "What year did the United States land the first man on the Moon?", "options": ["1965", "1969", "1971", "1975"], "answer": "1969"},
        {"question": "Which event led to the United States entering World War II?", "options": ["Attack on Pearl Harbor", "D-Day", "Battle of Midway", "Signing of the Treaty of Versailles"], "answer": "Attack on Pearl Harbor"},
        {"question": "Who was the 16th President of the United States?", "options": ["Andrew Johnson", "Abraham Lincoln", "Ulysses S. Grant", "James Buchanan"], "answer": "Abraham Lincoln"},
        {"question": "Which U.S. state was the last to join the Union?", "options": ["Alaska", "Hawaii", "California", "Arizona"], "answer": "Hawaii"},
        {"question": "What was the main purpose of the Lewis and Clark expedition?", "options": ["To explore the Louisiana Territory", "To fight Native American tribes", "To find gold in California", "To establish trade routes with China"], "answer": "To explore the Louisiana Territory"},
        {"question": "What was the name of the U.S. policy aimed at containing the spread of communism during the Cold War?", "options": ["Marshall Plan", "New Deal", "Monroe Doctrine", "Truman Doctrine"], "answer": "Truman Doctrine"},
        {"question": "Which U.S. President delivered the Gettysburg Address?", "options": ["Abraham Lincoln", "George Washington", "Thomas Jefferson", "Woodrow Wilson"], "answer": "Abraham Lincoln"}
],
    "soccer": [
        {"question": "Which country won the first FIFA World Cup in 1930?", "options": ["Brazil", "Argentina", "Germany", "Uruguay"], "answer": "Uruguay"},
        {"question": "Who is the all-time top scorer in the history of the FIFA World Cup?", "options": ["Cristiano Ronaldo", "Miroslav Klose", "Pele", "Lionel Messi"], "answer": "Miroslav Klose"},
        {"question": "Which club is known as 'The Red Devils'?", "options": ["Arsenal", "Manchester United", "Liverpool", "Chelsea"], "answer": "Manchester United"},
        {"question": "Who won the 2020 UEFA Champions League?", "options": ["Bayern Munich", "Paris Saint-Germain", "Liverpool", "Manchester City"], "answer": "Bayern Munich"},
        {"question": "Which country is home to the famous soccer player Lionel Messi?", "options": ["Brazil", "Argentina", "Portugal", "Spain"], "answer": "Argentina"},
        {"question": "Who holds the record for the most goals scored in the Premier League?", "options": ["Wayne Rooney", "Sergio Agüero", "Alan Shearer", "Cristiano Ronaldo"], "answer": "Alan Shearer"},
        {"question": "Which soccer player is known as 'CR7'?", "options": ["Neymar", "Cristiano Ronaldo", "Kylian Mbappé", "Lionel Messi"], "answer": "Cristiano Ronaldo"},
        {"question": "Which country won the 2018 FIFA World Cup?", "options": ["France", "Croatia", "Germany", "Brazil"], "answer": "France"},
        {"question": "What is the name of Barcelona's home stadium?", "options": ["Old Trafford", "Camp Nou", "Santiago Bernabéu", "Anfield"], "answer": "Camp Nou"},
        {"question": "Who won the Ballon d'Or in 2021?", "options": ["Robert Lewandowski", "Lionel Messi", "Cristiano Ronaldo", "Mohamed Salah"], "answer": "Lionel Messi"},
        {"question": "Which soccer club is known as 'Los Blancos'?", "options": ["Barcelona", "Real Madrid", "Juventus", "AC Milan"], "answer": "Real Madrid"},
        {"question": "Which country has won the most World Cups?", "options": ["Brazil", "Germany", "Italy", "Argentina"], "answer": "Brazil"},
        {"question": "Which player scored the 'Hand of God' goal in the 1986 World Cup?", "options": ["Diego Maradona", "Pele", "Zinedine Zidane", "Cristiano Ronaldo"], "answer": "Diego Maradona"},
        {"question": "Which country hosted the 1998 FIFA World Cup?", "options": ["France", "Brazil", "Italy", "South Korea"], "answer": "France"},
        {"question": "Which team won the first ever Premier League title in 1993-94?", "options": ["Manchester United", "Liverpool", "Arsenal", "Blackburn Rovers"], "answer": "Manchester United"}
],
    "gaa": [
        {"question": "Which county has won the most All-Ireland Senior Football Championships?", "options": ["Kerry", "Dublin", "Cork", "Meath"], "answer": "Kerry"},
        {"question": "Who is the all-time top scorer in the history of the GAA football?", "options": ["Jack O'Shea", "Colm Cooper", "Bernard Brogan", "Ciarán Kilkenny"], "answer": "Colm Cooper"},
        {"question": "What year was the GAA founded?", "options": ["1884", "1890", "1875", "1901"], "answer": "1884"},
        {"question": "Which county won the 2020 All-Ireland Senior Hurling Championship?", "options": ["Kilkenny", "Limerick", "Cork", "Tipperary"], "answer": "Limerick"},
        {"question": "Which GAA team is known as the 'Kingdom'?", "options": ["Kerry", "Dublin", "Cork", "Galway"], "answer": "Kerry"},
        {"question": "What is the name of the famous GAA stadium in Dublin?", "options": ["Croke Park", "Páirc Uí Chaoimh", "Semple Stadium", "Dr. Hyde Park"], "answer": "Croke Park"},
        {"question": "Which county is known as the 'Shamrocks' in GAA?", "options": ["Kilkenny", "Dublin", "Cork", "Antrim"], "answer": "Kilkenny"},
        {"question": "Who holds the record for the most All-Ireland Hurling titles?", "options": ["Kilkenny", "Cork", "Wexford", "Limerick"], "answer": "Kilkenny"},
        {"question": "Which player is considered one of the greatest Gaelic footballers of all time and is known as 'The Gooch'?", "options": ["Paul Galvin", "Colm Cooper", "Mick O'Connell", "Brian Fenton"], "answer": "Colm Cooper"},
        {"question": "Which county has won the most All-Ireland Senior Hurling Championships?", "options": ["Kilkenny", "Cork", "Limerick", "Clare"], "answer": "Kilkenny"},
        {"question": "Which team won the 2022 All-Ireland Senior Football Championship?", "options": ["Dublin", "Mayo", "Tyrone", "Kerry"], "answer": "Kerry"},
        {"question": "What is the name of the competition for GAA clubs at the national level?", "options": ["All-Ireland Championship", "Leinster Championship", "Club Championship", "Provincial Championship"], "answer": "Club Championship"},
        {"question": "Who won the All-Ireland Senior Football Championship in 2018?", "options": ["Dublin", "Mayo", "Kerry", "Galway"], "answer": "Dublin"},
        {"question": "Which GAA legend is famous for his partnership with Henry Shefflin in the Kilkenny hurling team?", "options": ["Michael Fennelly", "Richie Hogan", "TJ Reid", "Eoin Larkin"], "answer": "Eoin Larkin"},
        {"question": "Which province does the county of Tipperary belong to in GAA competitions?", "options": ["Leinster", "Munster", "Connacht", "Ulster"], "answer": "Munster"}
],
    "mma": [
        {"question": "Who is known as the 'Notorious' in the UFC?", "options": ["Khabib Nurmagomedov", "Conor McGregor", "Nate Diaz", "Jorge Masvidal"], "answer": "Conor McGregor"},
        {"question": "Which UFC fighter holds the record for the most title defenses in the men's flyweight division?", "options": ["Demetrious Johnson", "Henry Cejudo", "Deiveson Figueiredo", "Brandon Moreno"], "answer": "Demetrious Johnson"},
        {"question": "What is the name of the UFC's official championship belt?", "options": ["The Golden Belt", "The UFC Title", "The Fight Belt", "The Octagon Belt"], "answer": "The UFC Title"},
        {"question": "Who was the first woman to win a UFC title?", "options": ["Amanda Nunes", "Ronda Rousey", "Valentina Shevchenko", "Joanna Jędrzejczyk"], "answer": "Ronda Rousey"},
        {"question": "Which fighter has the most UFC knockouts?", "options": ["Chuck Liddell", "Anderson Silva", "Derrick Lewis", "Vitor Belfort"], "answer": "Derrick Lewis"},
        {"question": "Which MMA promotion did Conor McGregor make his UFC debut in?", "options": ["Bellator", "UFC", "Cage Warriors", "Strikeforce"], "answer": "Cage Warriors"},
        {"question": "Who won the first season of 'The Ultimate Fighter'?", "options": ["Brock Lesnar", "Kenny Florian", "Diego Sanchez", "Forrest Griffin"], "answer": "Forrest Griffin"},
        {"question": "Which fighter is known as 'The Spider' in MMA?", "options": ["Jon Jones", "George St-Pierre", "Anderson Silva", "Demetrious Johnson"], "answer": "Anderson Silva"},
        {"question": "Who was the first fighter to hold two UFC belts simultaneously?", "options": ["Daniel Cormier", "Conor McGregor", "Amanda Nunes", "Henry Cejudo"], "answer": "Conor McGregor"},
        {"question": "Which fighter was known as 'The Phenom'?", "options": ["Vitor Belfort", "Randy Couture", "Chuck Liddell", "Nate Diaz"], "answer": "Vitor Belfort"},
        {"question": "What is the maximum weight limit for the UFC lightweight division?", "options": ["170 lbs", "155 lbs", "145 lbs", "135 lbs"], "answer": "155 lbs"},
        {"question": "Which UFC fighter is known for his nickname 'Bones'?", "options": ["Jon Jones", "Randy Couture", "Stipe Miocic", "Daniel Cormier"], "answer": "Jon Jones"},
        {"question": "Who did Khabib Nurmagomedov defeat to win the UFC Lightweight Championship?", "options": ["Conor McGregor", "Tony Ferguson", "Dustin Poirier", "Edson Barboza"], "answer": "Conor McGregor"},
        {"question": "Which UFC fighter was known for his intense rivalry with Chael Sonnen?", "options": ["Anderson Silva", "Michael Bisping", "Dan Henderson", "Frankie Edgar"], "answer": "Anderson Silva"},
        {"question": "Which MMA fighter is known as the 'Cyborg'?", "options": ["Holly Holm", "Amanda Nunes", "Cris Cyborg", "Gina Carano"], "answer": "Cris Cyborg"}
]





}
